### PR TITLE
Fix/destroy resolve

### PR DESCRIPTION
**Pull request by jspizziri**
In the interest of time I created a new PR to address the issues with [the one submitted by @mmmoussa ](https://github.com/doublesymmetry/react-native-track-player/pull/1441).

### CODE REVIEW

**Review by dcvz — APPROVED** [review]
LGTM 👍

**Comment by mpivchev** [comment]
Let's merge this after #1447 has been fixed.

**Comment by dcvz** [comment]
@jspizziri since we merged `kotlinaudio` we'll need to reopen this PR. Sorry!

**Comment by jspizziri** [comment]
Reopened https://github.com/doublesymmetry/react-native-track-player/pull/1500

**Pull request closed without merging**
