### PR TITLE
Replace stopWithApp key with stoppingAppPausesPlayback in typescript sources and documentations

### PR DESCRIPTION
**Pull request by nicomontanari**

### CODE REVIEW

**Comment by mpivchev** [comment]
Thanks for the addition :)

**Comment by nicomontanari** [comment]
You are welcome! 😃

**Comment by jspizziri** [comment]
@nicomontanari @mpivchev , Sorry I'm late on this, but can we create an alias for `stopWithApp` that points to `stoppingAppPausesPlayback` so we don't create a breaking change?

**Comment by nicomontanari** [comment]
@jspizziri it may be an idea, if you decide to do it I could make these changes

**Pull request merged**
