### PR TITLE
Feature: Windows Support

### PR DESCRIPTION
**Pull request by dcvz**

### CODE REVIEW

**Comment by dcvz** [comment]
@tritao what was the outcome with your manager. I've tried getting started on finishing this off but could still use some C++ expertise to get this finished.

**Comment by tritao** [comment]
I'm currently porting another module which is the priority, but can take look at this once done.

I see you added some CI as well as updated to the index-based version, so what can I help with?

**Comment by dcvz** [comment]
Adding the support for index based queue methods. I've tried adding it based on the previous PR of yours but they're not completely working yet, although the module does compile. I'm not able to debug this effectively though however as I don't have a dedicated machine that I can use all the time. 

If we can fix up this PR we can merge and release it along @v2.

**Comment by tritao** [comment]
Hey @dcvz, just to inform that I'll be able to take a look at this next week. Hopefully we can get it over the line.

**Comment by dcvz** [comment]
Great to hear @tritao!

**Comment by tritao** [comment]
@dcvz I've pushed some fixes to a new branch: https://github.com/JaneaSystems/react-native-track-player/tree/feature/windows-cpp-v2

Its working with the Windows example:

ApplicationFrameHost_83FLyHsLtS

**Comment by dcvz** [comment]
Thanks @tritao 🙏 I'll have some time to check it out tomorrow and get it merged!

**Comment by asklar** [comment]
Hey @dcvz did you get a chance to try this out? we'd love to get the windows support added to this module!
cc @chiaramooney

**Review by chiaramooney — DISMISSED** [review]
👍

**Comment by dcvz** [comment]
thanks for this @tritao, as mentioned I don't have a windows dev machine so it took me a while to test. I was able to test the example and review the changes and to looks good!

I'll acquire a windows dev machine soon to help keep the windows port moving forward with the rest of the module. I may have to ask you @asklar for some pointers on getting VS setup properly. Didn't manage to get it fully working (with autocompletion) last time.

**Comment by asklar** [comment]
thanks @dcvz ! 
We have a Discord channel for react native windows in the _UWP Community_ Discord server, we'd love to have you join :) https://discord.gg/rGug9Jj8

**Comment by dcvz** [comment]
Hi @asklarit sorry for the late reply, I thought I'd be able to use the link any time but it looks like the link has expired.

Do you mind sharing another? I'll act on this one quickly!

**Comment by asklar** [comment]
> Hi @asklarit sorry for the late reply, I thought I'd be able to use the link any time but it looks like the link has expired.
> 
> Do you mind sharing another? I'll act on this one quickly!

sure just click on the link at https://uwpcommunity.com/

**Pull request merged**
