### PR TITLE
fix: don't overwrite previous progress interval when it's unspecified in updateOptions

### PR DESCRIPTION
**Pull request by fivecar**
Previous code would clear/overwrite your progress interval if you called `updateOptions` without re-specifying the same interval. This change conforms the code to the documentation by preserving your previous progress interval if a new call to `updateOptions` doesn't specify a new interval.

### CODE REVIEW

**Review by bradleyflood — COMMENTED** [review]
LGTM

**Comment by fivecar** [comment]
@dcvz : Just a gentle ping on whether this looks good to merge...

**Comment by fivecar** [comment]
@dcvz / @bradleyflood  : The platform validation is failing on not finding `rexml/document`, but it's really quite unlikely that this PR caused it. Could you LMK if this is a known issue that's fixable?

**Comment by fivecar** [comment]
Fix for break submitted in #1869. Once that lands, this should pass.

**Pull request closed without merging**
