### PR TITLE
fix(ios, android): implement parity between android and ios for playb…

### PR DESCRIPTION
**Pull request by jspizziri**
…ack-track-changed event 
 
#1462, #1349, #1389, #1311

### CODE REVIEW

**Comment by jspizziri** [comment]
I still need to update this based on the updates in `SwiftAudioEx`.

**Comment by jspizziri** [comment]
[Migrating this table from the previous PR as I think it's good context](https://github.com/doublesymmetry/react-native-track-player/pull/1482#issuecomment-1105252330):

# Notes (iOS)

The following matrices document _WHEN_ a `player.event.queueIndex` event is emitted.

## Multi-Track Queue
|                  | Natural Track End - Queue Middle | Natural Track End - Queue End | Skip - Queue Middle | Skip - Queue End |
|------------------|----------------------------------|-------------------------------|---------------------|------------------|
| **RepeatMode.Off**   | ✅ | ❌ | ✅ | ❌ | 
| **RepeatMode.Track** | ❌ | ❌ | ✅ | ❌ | 
| **RepeatMode.Queue** | ✅ | ✅ | ✅ | ✅ | 

**Note:** no `Skip - Queue End` event is fired for `Off` and `Track` as there is no "next" track to go to logically. Skip is truly designed to advance the track position in the queue. In `RepeatMode.Queue` it can logically proceed to another track which is the beginning of the queue (however this is not the case when a single track is in the queue).

 
## Single-Track Queue

**Note:** in this case middle and end of queue are exactly equal in meaning

|                  | Natural Track End - Queue Middle | Natural Track End - Queue End | Skip - Queue Middle | Skip - Queue End |
|------------------|----------------------------------|-------------------------------|---------------------|------------------|
| **RepeatMode.Off**   | ❌  | ❌  | ❌ | ❌ |
| **RepeatMode.Track** | ❌  | ❌  | ❌ | ❌ |
| **RepeatMode.Queue** | ❌⚠️ | ❌⚠️ | ❌ | ❌ |

⚠️** [denotes scenarios in which playback is not properly repeated.](https://github.com/doublesymmetry/react-native-track-player/issues/1483)

**Comment by jspizziri** [comment]
@dcvz would it be possible for you to give me a quick breakdown of the new expected behavior from https://github.com/doublesymmetry/SwiftAudioEx/pull/16

Thanks!

**Comment by dcvz** [comment]
@jspizziri it should fire now correct in all places except Skip - Queue End event for Off and Track as there is no "next" track to go to logically.

**Comment by jspizziri** [comment]
TODO: https://github.com/doublesymmetry/react-native-track-player/issues/1293

**Comment by jspizziri** [comment]
Remaining Issues:

1. In a single-track queue with `RepeatMode.Queue` Android on "Skip" **no** track-changed is fired.
    - Should be fired with `nextTrack`, `position`, and `track` (according to iOS).
    - Natural track end works correctly.

**Comment by jspizziri** [comment]
@dcvz with the exception of [this issue](https://github.com/doublesymmetry/react-native-track-player/pull/1501#issuecomment-1110096083) I think this is good to go.

**Comment by jspizziri** [comment]
@curthipster would appreciate if you could test.

**Comment by dcvz** [comment]
@jspizziri wrote some unit tests in `KotlinAudio` I'm seeing more cases fail:

- Repeat mode - Track
  - two items in queue - first item naturally ending does not emit the event (does repeat track)
  - one item in queue - item naturally ending does not emit event (does repeat track)
  - one item in queue - pressing next does not emit event (calling next does not do anything, does not restart track)
  
- Repeat mode - Queue
  - one item in queue - item naturally ending does not emit event (does repeat track)
    - one item in queue - pressing next does not emit event (does repeat track)
    
Are you sure you only experienced this one case?

**Comment by jspizziri** [comment]
@dcvz not 100% sure. I'll retest those now and get back to you.

**Comment by dcvz** [comment]
Thanks for this @jspizziri! This helps a lot. There might be something up with the test setup or something changed between the current used version. I'll dig a bit!

**Comment by jspizziri** [comment]
Please note that this PR also addresses/fixes the issues discussed discussed here https://github.com/doublesymmetry/react-native-track-player/issues/1311

**Comment by bradleyflood** [comment]
Awesome work @jspizziri

**Comment by jspizziri** [comment]
@dcvz if you push up your android work for `KotlinAudio` I'd be happy to finish it off so we can put this one to bed.

**Comment by jspizziri** [comment]
Update on this:

There was work done on [the KotlinAudio `exploration/fix-tests` branch](https://github.com/doublesymmetry/KotlinAudio/tree/exploration/fix-tests) to add test cases for the scenarios above.

What remains to be done is:

1. Complete writing the test cases.
2. Fix the failing cases.

**Comment by jspizziri** [comment]
@dcvz I've retested this and it works as we understood it. I created a new dedicated issue for the remaining work https://github.com/doublesymmetry/react-native-track-player/issues/1612

I think we can merge this now.

**Comment by jspizziri** [comment]
Also created this issue https://github.com/doublesymmetry/react-native-track-player/issues/1613 as it was reported in an attached issue that was partially resolved by this PR. I'm going to close the old ticket so we have a fresh dedicated issue for the remaining problem.

**Pull request merged**
