### PR TITLE
internal: Ensure to set AudioSession configuration on iOS

### PR DESCRIPTION
**Pull request by Spice-Z**
PR for https://github.com/doublesymmetry/react-native-track-player/issues/1790

Call `AVAudioSession.sharedInstance().setCategory` every time `play` method is called.

### CODE REVIEW

**Comment by bradleyflood** [comment]
Hmm. I assume most RNTP users don't have this problem or need. 

Can't you just call 'setup()' again when your app is returning to this module?

**Comment by bradleyflood** [comment]
I say that because my app doesn't use any other audio library so I don't have this problem. 

Yet my users do call the pause and play methods hundreds of times per session. So this PR change seems like an intrusive change that would be impacting the majority of RNTP only users to solve a specific use-case problem. 

I feel like there has to be a better way?

**Comment by Spice-Z** [comment]
> Can't you just call 'setup()' again when your app is returning to this module?

I tried, but app will crash when setup is called multiple time. (I have to destroy player, but RNTP doesn't have `destory` method now)


And in trial PR, @puckey  suggested [better idea](https://github.com/doublesymmetry/react-native-track-player/issues/1790#issuecomment-1274238673)!

> How about adding iosCategory, iosCategoryMode, iosCategoryOptions as options to TrackPlayer.updateOptions() instead?


@bradleyflood 
How do you think about this?
I think extending updateOptions is very good.

**Comment by bradleyflood** [comment]
@Spice-Z Good idea!

**Comment by Spice-Z** [comment]
Ok, I will make new PR for extending updateOptions!

**Pull request closed without merging**
