### PR TITLE
Removed Android service

### LINKED ISSUE #343: App Not Working Properly :Player-Handler using Redux for React Native v0.57.4 and react-native-track-player v 1.0.0 For Android
**I Know there is an example of it including in this package And I followed it**. 
My App Sometime Run and some time App stops on Android. But When I run in Debug mode I saw two warning about store.
`Warning : Failed child context type: The child context 'store' is marked as required in 'Provider', but its value is "null"`

And then On My Audio Screen

`Error: Invariant Voilation:Could not find "store" in either the context or props of "Connect(AudioScreen)". Either wrap the root component in a <Provider>. or explicitly pass "store" as a prop to "Connect(AudioScreen)"`
What am I Doing Wrong??
________________________________________________________________________________________________________________
index.js:
```
import {AppRegistry} from 'react-native';
import { createStore, applyMiddleware } from 'redux';
import thunkMiddleware from 'redux-thunk';
import App from './App';
import TrackPlayer from 'react-native-track-player';
import EventHandler from './player-handler';
import reducers from './reducers';
const store = createStore(reducers, applyMiddleware(thunkMiddleware));
AppRegistry.registerComponent("AudioApp", () => App(store));
TrackPlayer.registerEventHandler(EventHandler(store));
```
reducers.js:
```
import { combineReducers } from "redux";
import { ActionType } from "./action";
const merge = (pre, nex) => Object.assign({}, pre, nex);
const AudioStatus = (state = {}, action) => {
  if (
    action.type === ActionType.PLAY ||
    action.type === ActionType.PAUSE ||
    action.type === ActionType.STOP
  ) {
    return merge(state, {
      AudioStatus: action.payload
    });
  }
  return state;
};
const reducer = combineReducers({
  Audio: AudioStatus
});
export default reducer;
```
action.js
```
//================Action Types Constants
const PLAY = "PLAY",
  PAUSE = "PAUSE",
  STOP = "STOP",
  OperationDoing = "OperationDoing";

//================Action Creators
//ASYNC ACTION CREATOR
const ButtonOp = Type => async dispatch => {
  // dispatch({ type: OperationDoing });
  try {
    dispatch({ type: Type, payload: Type });
  } catch (e) {
    alert("Fishy Here");
  }
};

module.exports = {
  ButtonOp,
  ActionType: {
    PLAY,
    PAUSE,
    STOP,
    OperationDoing
  }
};

```
App.js

```
import React from "react";
import { View, StatusBar, AppState } from "react-native";
import AudioScreen from "./AudiosScreen";
import { Provider } from "react-redux";
import TrackPlayer from "react-native-track-player";
import Orientation from "react-native-orientation-locker";
class App extends React.PureComponent {
  static store = null;
  constructor(props) {
    super(props);
  }
  componentWillMount() {
    Orientation.lockToPortrait();
  }
  async componentWillUnmount() {
    try {
      await TrackPlayer.destroy();
    } catch (e) {}
  }
  componentDidMount() {
    TrackPlayer.setupPlayer({}).then(() => {
      TrackPlayer.updateOptions({
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP
        ],
        stopWithApp: true,
        color: 0x2ecc71
      });
    });
  }
render() {
    return (
      <View style={{ flex: 1 }}>
        <StatusBar hidden={true} />
          <Provider store={App.store}>
            <AudioScreen />
          </Provider>
      </View>
    );
  }
}

module.exports = function(store) {
  App.store = store;
  return App;
};
```
player-handler.js
```
import { ButtonOp, ActionType } from "./action";

async function eventHandler(store, data) {
  switch (data.type) {
    case "remote-play":
      store.dispatch(ButtonOp(ActionType.PLAY));
      break;
    case "remote-pause":
      store.dispatch(ButtonOp(ActionType.PAUSE));
      break;
    case "remote-stop":
      store.dispatch(ButtonOp(ActionType.STOP));
      break;
  }
}

module.exports = function(store) {
  return eventHandler.bind(null, store);
};
```

### LINKED ISSUE #391: java.lang.IllegalStateException
hi, I recensed new bug in google play.

java.lang.IllegalStateException
com.guichaguri.trackplayer.module.MusicModule.waitForConnection

Hier, 14:25 sur la version 10 de l'application
Huawei Mate 10 lite (HWRNE), Android 8.0
Rapport 1 sur 1
java.lang.IllegalStateException: 
  at android.app.ContextImpl.startServiceCommon (ContextImpl.java:1701)
  at android.app.ContextImpl.startService (ContextImpl.java:1657)
  at android.content.ContextWrapper.startService (ContextWrapper.java:644)
  at android.content.ContextWrapper.startService (ContextWrapper.java:644)
  at com.guichaguri.trackplayer.module.MusicModule.waitForConnection (MusicModule.java:100)
  at com.guichaguri.trackplayer.module.MusicModule.add (MusicModule.java:183)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.facebook.react.bridge.JavaMethodWrapper.invoke (JavaMethodWrapper.java:372)
  at com.facebook.react.bridge.JavaModuleWrapper.invoke (JavaModuleWrapper.java:160)
  at com.facebook.react.bridge.queue.NativeRunnable.run (Native Method)
  at android.os.Handler.handleCallback (Handler.java:808)
  at android.os.Handler.dispatchMessage (Handler.java:101)
  at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage (MessageQueueThreadHandler.java:29)
  at android.os.Looper.loop (Looper.java:166)
  at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run (MessageQueueThreadImpl.java:192)
  at java.lang.Thread.run (Thread.java:784)

### LINKED ISSUE #473: [Android] Crash - Not allowed to start service Intent
# Configuration
package.json
```
    "react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-track-player": "^1.1.2",
    "react-native-swift": "^1.2.2",
```

react-native info
```
Environment:
  OS: macOS High Sierra 10.13.6
  Node: 8.11.2
  Yarn: 1.9.4
  npm: 5.6.0
  Watchman: 4.9.0
  Xcode: Xcode 10.1 Build version 10B61
  Android Studio: 3.2 AI-181.5540.7.32.5056338

Packages: (wanted => installed)
  react: 16.3.1 => 16.3.1
  react-native: 0.55.4 => 0.55.4
```

# Problem 
I am having more and more of the same crash on Android using the version 1.1.2, here is the stack :
```
Fatal Exception: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.xxx/com.guichaguri.trackplayer.service.MusicService }: app is in background uid UidRecord{39a05c9 u0a454 CEM  bg:+1m5s685ms idle procs:1 seq(0,0,0)}
       at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1538)
       at android.app.ContextImpl.startService(ContextImpl.java:1484)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at android.content.ContextWrapper.startService(ContextWrapper.java:663)
       at com.guichaguri.trackplayer.module.MusicModule.waitForConnection(MusicModule.java:100)
       at com.guichaguri.trackplayer.module.MusicModule.getPosition(MusicModule.java:405)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:789)
       at android.os.Handler.dispatchMessage(Handler.java:98)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
       at android.os.Looper.loop(Looper.java:164)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
       at java.lang.Thread.run(Thread.java:764)
```

*service.js*
```
module.exports = async function service() {
  TrackPlayer.addEventListener('remote-play', () => {
    MyPlayer.playTrack(() => {});
  });

  TrackPlayer.addEventListener('remote-pause', () => {
    MyPlayer.pauseTrack(() => {});
  });

  TrackPlayer.addEventListener('remote-seek', (time) => {
    TrackPlayer.seekTo(time.position);
  });

  TrackPlayer.addEventListener('remote-jump-backward', (time) => {
    TrackPlayer.getPosition().then((position) => {
      TrackPlayer.seekTo(position - time.interval);
    });
  });

  TrackPlayer.addEventListener('remote-jump-forward', (time) => {
    TrackPlayer.getPosition().then((position) => {
      TrackPlayer.seekTo(position + time.interval);
    });
  });

  TrackPlayer.addEventListener('remote-stop', () => {
    MyPlayer.stopTrack(() => {});
  });

  TrackPlayer.addEventListener('playback-queue-ended', (infos) => {
    console.log('ended', infos);
    if (infos && infos.track) {
      MyPlayer.stopTrack(() => {});
    }
  });
};

```

# Question 
Is this solved in the newest version `1.1.3`? Cause I saw a bug correction that looks like this on the last version. ==> It's not solved in `1.1.3`

Is there any workaround or maybe some configuration I am missing? 

Thanks a lot

### LINKED ISSUE #524: Context.startForegroundService() did not then call Service.startForeground()
Good afternoon,
I had already commented on this error and had given it as "solved", but apparently the same still has problems.

Can it be "initialization" error of the component in React?

screencapture-play-google-apps-publish-2019-04-02-14_08_09

Info `
Context.startForegroundService() did not then call Service.startForeground(), InvisibleToUser`:
screencapture-play-google-apps-publish-2019-04-04-15_12_20

Info `Context.startForegroundService() did not then call Service.startForeground(): ServiceRecord{ba33f34 u0 com.hunterfm/com.guichaguri.trackplayer.service.MusicService}`:
screencapture-play-google-apps-publish-2019-04-04-15_15_04

### LINKED ISSUE #620: [Android] Crash - android.app.RemoteServiceException
i am getting crash logs on playstore for some of the devices:
```
android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1872)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7045)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
i tested on some of the devices it's working properly. i updated react native track player and target sdk version to 28. any idea why this crash happening ?

i am attaching Android versions and devices info on which crashes happens:

Screen Shot 2019-06-08 at 8 21 09 PM

### LINKED ISSUE #732: URGENT: Trackplayer is not removed from memory when app closes
Using trackplayer 1.20.

I see the app stays in memory even when using StopWithApp = true.
It looks like there are two instances fired and one is going down after app and other stays in memory. 

Also i can confirm that the app stays in the background as i get reports data traffic is out in 4 days.

Where do i need to look to solve this?

My part of loading: (maybe buggy haha)

```
import React, { Component, useEffect, useState } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image,
  TouchableOpacity,
} from 'react-native';
import { connect } from 'react-redux';
import { togglePlayer } from '../actions';
import NetInfo from '@react-native-community/netinfo';

import TrackPlayer, { usePlaybackState } from 'react-native-track-player';

import * as playerSetting from '../constants/PlayerConstants';
import * as screenSetting from '../constants/ScreenConstants';

const { playerUrl } = playerSetting;
const { width, height } = screenSetting;

function Player(props) {
  const playbackState = usePlaybackState();
  const [haveInternet, setHaveInternet] = useState(true);

  useEffect(
    () => {
      //Event Listeners
      NetInfo.addEventListener(
        'connectionChange',
        handleFirstConnectivityChange
      );
      function handleFirstConnectivityChange() {
        TrackPlayer.reset();
        if (Platform.OS === 'ios') {
          togglePlayback();
        }
      }

      NetInfo.isConnected.addEventListener(
        'connectionChange',
        this.handleConnectivityChange
      );

      NetInfo.isConnected.fetch().done((isConnected) => {
        if (isConnected == true) {
          setHaveInternet(true);
        }
      });
      TrackPlayer.setupPlayer({});
      TrackPlayer.updateOptions({
        stopWithApp: true,
        //waitForBuffer: true,
        capabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
          TrackPlayer.CAPABILITY_STOP,
        ],
        compactCapabilities: [
          TrackPlayer.CAPABILITY_PLAY,
          TrackPlayer.CAPABILITY_PAUSE,
        ],
      });

      return () => {
        //TrackPlayer.destroy();
        NetInfo.isConnected.removeEventListener(
          'connectionChange',
          this.handleConnectivityChange
        );
        NetInfo.removeEventListener(
          'connectionChange',
          handleFirstConnectivityChange
        );
      };
    },
    [TrackPlayer.stop(), TrackPlayer.reset()]
  );

  handleConnectivityChange = (isConnected) => {
    if (isConnected == false) {
      setHaveInternet(false);
      //togglePlayback();
    } else {
      setHaveInternet(true);
      //togglePlayback();
    }
  };

  renderButton = () => {
    if (
      playbackState == TrackPlayer.STATE_PAUSED ||
      playbackState === TrackPlayer.STATE_STOPPED ||
      playbackState === TrackPlayer.STATE_NONE
    ) {
      return (
        <Image
          source={require('../assets/play.png')}
          style={styles.playerButton}
          imageStyle={{ resizeMode: 'contain' }}
        />
      );
    } else {
      return (
        <Image
          source={require('../assets/pauze.png')}
          style={styles.playerButton}
          imageStyle={{ resizeMode: 'contain' }}
        />
      );
    }
  };

  async function togglePlayback() {
    const currentTrack = await TrackPlayer.getCurrentTrack();
    if (currentTrack == null) {
      await TrackPlayer.add({
        id: 'HeteHits',
        url: playerUrl,
        title: 'Loading...',
        artist: 'Loading...',
        artwork: '../assets/track_image.png',
      });
      await TrackPlayer.play();
      props.togglePlayerState();
    } else {
      if (playbackState === TrackPlayer.STATE_PAUSED) {
        await TrackPlayer.play();
        props.togglePlayerState();
      } else {
        TrackPlayer.pause();
        props.togglePlayerState();
      }
    }
  }

  return (
    <View style={styles.container}>
      <TouchableOpacity
        disabled={!haveInternet}
        onPress={() => togglePlayback()}
      >
        <View
          style={{
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
          }}
        >
          {renderButton()}
          <Image
            source={require(`../assets/luisterLive.png`)}
            style={{
              height: height * 0.075,
              width: width * 0.175,
              resizeMode: 'contain',
            }}
            imageStyle={{ resizeMode: 'contain' }}
          />
        </View>
      </TouchableOpacity>
    </View>
  );
}

const mapStateToProps = (state) => {
  return {
    speeltNu: state.togglePlayer.speeltNu,
  };
};

const mapDispatchToProps = (dispatch) => {
  return {
    togglePlayerState: () => dispatch(togglePlayer()),
  };
};

export default connect(mapStateToProps, mapDispatchToProps)(Player);

const styles = StyleSheet.create({
  container: {
    justifyContent: 'center',
    alignItems: 'center',
  },
  playerButton: {
    height: height * 0.07,
    width: width * 0.17,
    resizeMode: 'contain',
    marginBottom: 10,
  },
});

```

### LINKED ISSUE #812: Notification Button Actions causing TrackPlayer crash
#### Configuration
`react-native info`
```
System:
    OS: Linux 4.15 Ubuntu 18.04.3 LTS (Bionic Beaver)
    CPU: (16) x64 AMD Ryzen 7 2700X Eight-Core Processor
    Memory: 5.77 GB / 31.40 GB
    Shell: 5.4.2 - /usr/bin/zsh
  Binaries:
    Node: 12.13.1 - /usr/local/bin/node
    Yarn: 1.19.2 - /usr/bin/yarn
    npm: 6.12.1 - /usr/local/bin/npm
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.1 => 0.61.1 
  npmGlobalPackages:
    react-native-git-upgrade: 0.2.7
```
#### What `react-native-track-player` version are you using?
`1.2.0` from `master`, I've also tried `1.1.8` from NPM

# Issue
I'm getting
```
Service com.guichaguri.trackplayer.service.MusicService has leaked IntentReceiver com.guichaguri.trackplayer.service.MusicManager$1@8941f18 that was originally registered here. Are you missing a call to unregisterReceiver()?
```
in the android logs when triggering remote events from the notification on `RN 0.61.1` and `Android 9 & 10`.
 I'm also using RNN (`react-native-navigation`) 4.0.5.
The `TrackPlayer.getState()` will show the state change to `STATE_STOPPED`, but the audio keeps playing in the background. If I load a new track in, it will play over the original track in the background.

I'm using 

`App.js`
```
Navigation.events().registerAppLaunchedListener(() => {
      TrackPlayer.setupPlayer().then(async ()=>{
            await TrackPlayer.registerPlaybackService(() => require('./service.js'));
            await TrackPlayer.updateOptions({
                    stopWithApp: true,
                    capabilities: [
                      TrackPlayer.CAPABILITY_STOP,
                    ],
            });
      });
});
```

`service.js`
```
import TrackPlayer  from 'react-native-track-player';
module.exports = async ()=>{
    TrackPlayer.addEventListener('remote-stop', () => {
        TrackPlayer.stop();
    });
};

```

### LINKED ISSUE #813: [Android] App process lives on after quitting by removing app from recents
# Configuration

`react-native-track-player` version 1.1.8
Using example app from this repo.

# Issue

On Android, launch the example app.

Use the following command to verify the app is running. A pid number will be given.
```
adb shell pidof com.example
```

Do not go past the initial screen of the demo UI.

Quit the app by swiping it away in the multi-tasking / recent apps menu.

Use the same command to check again. The process no longer exists, as expected.

Launch the app again, and verify a new process ID exists.

This time, proceed to the playlist example and start playing a track.

Quit the app again.

Check the process again. 

This time, even though the playback has stopped, and the app does not appear in the recent apps menu, the process still exists.

This circumstance is leading to strange behavior in my app because my redux store remains intact at this point, even though both the main activity and the music service have been destroyed. When the app is re-launched, my redux store exists as it did when the app was "quit", however, the activity is re-created, and so is the music service.

**Is there some configuration that can be changed so that the process fully quits as would seem intuitive?**

# Code

I am using `stopWithApp: true` in my app, just like the example. So, that further underscores the expectation that once the app is "quit" it shouldn't exist at all.

### PR DESCRIPTION
**Pull request by Guichaguri**
This PR removes the Android service in favor of the in-app playback.

**Pros**
* Fixes #473
* Fixes #391
* Fixes #732
* Fixes #813 
* Fixes #812 
* Fixes #524 
* Fixes #343 
* Might fix #620
* Closer behavior of both platforms
* Possibly Expokit support

**Cons**
* Android may possibly kill the app while playing in order to reduce system resource usage. We'll have to figure out how frequently it happens and how to prevent that from happening.
* The player won't be able to play while the app is closed. This is a feature that is usually disabled through the `stopWithApp` option by the majority of the apps anyway.
* This was a big differential from other music modules, as it was closer to a native music app, but I figured that react-native doesn't work properly with services nor the community wants to work with native behavior like this.

---

As this is a big change on Android, I'd love to see testing here from all sorts of apps.

### CODE REVIEW

**Comment by puckey** [comment]
I would be happy to test this out on some Android phones to see how long it takes for the app to be killed.

However, I do wonder if this is the right direction. For a music player having music stop at random moments feels like a more existential issue than intermittent crashes for a small subset of users. (0.8% in our radio-player case)

Our use-case is a radio app, where I know users can listen to a station for up to 8 hours at a time - the chance that the app would be killed by the system during that time is pretty high.. and for a user it is not a nice experience to have to wonder why their music stopped playing.

Here is a related issue about background-audio on expo, where users report apps being killed after several minutes in the background: https://github.com/expo/expo/issues/4850

**Comment by ashishfeels** [comment]
@puckey i will love to try your radio app, also i will also be testing the online streaming. i would like to know does your app streams hls content or not as its more prominent on hls (m3u8) links

**Comment by puckey** [comment]
@ashishfeels here you go: https://play.google.com/store/apps/details?id=com.jonathanpuckey.radiogarden&hl=nl  We don't support HLS content right now, but it is on our roadmap.

**Comment by ashishfeels** [comment]
@Guichaguri can we make the error reporting better. i mean the type of error we get while playing the audio. like i was trying to play an hls content and it was giving me liveBehindWindow Error , but on js side it was only giving me playback error. that will help the issue in debugging the problems.

**Comment by Guichaguri** [comment]
@ashishfeels we definitely should, but that's for another PR.

**Comment by ashishfeels** [comment]
yes @Guichaguri that's just an idea as i tried to fix in my fork i don't know its correct or not but it works :P

**Comment by kyleclegg** [comment]
Happy to test this as well 👍

**Comment by samkuhn** [comment]
OMG guys isn't this the exact opposite of the correct direction? 

> This was a big differential from other music modules, as it was closer to a native music app, but I figured that react-native doesn't work properly with services nor the community wants to work with native behaviour like this.

Are you feeling ok? People have been screaming at you on Canny [since 2017](https://expo.canny.io/feature-requests/p/audio-playback-in-background) for proper background audio support and now you want to strip it out entirely because your implementation is crappy and theres a bunch of issues around it.

I opened [this issue](https://github.com/expo/expo/issues/4850) a year ago. It literally took me around 8 hours after ejecting to code up a proper foreground service myself that has worked flawlessly on Android ever since. While I can't share my code directly I did include a similar implementation by someone else that should work well AND a video from the ExoPlayer team describing exactly how it should be done properly.

I know, I know, volunteers working on this in their own free time blah blah, stop complaining. 

Sorry but seriously I'm getting a bit fed up of all the unfulfilled promises. Warning to anyone thinking of making an audio player app in Expo: DO NOT DO IT FOR GOD SAKE! 

Choose React Native and get three years of your life back.

**Comment by samkuhn** [comment]
Sorry left a bit of a snarky message thinking this was the Expo repo lol.

> This was a big differential from other music modules, as it was closer to a native music app, but I figured that react-native doesn't work properly with services nor the community wants to work with native behavior like this.

I'm not sure I agree with this and would definitely advise pushing on for full background audio. Expo has been [dallying for 3 years](https://expo.canny.io/feature-requests/p/audio-playback-in-background) on this subject much to everyone's dismay. I created [this issue](https://github.com/expo/expo/issues/4850) a year ago but ended up just ejecting from Expo and coding the foreground service myself following this [example](https://gist.github.com/Ochornma/0c66429c73e40ff57e12a790bdcba4a9) and [video](https://www.youtube.com/watch?v=svdq1BWl4r8). 

Our background playback has been working flawlessly since.

**Comment by puckey** [comment]
@samkuhn any chance you could delete your earlier message? It would be nice to keep the tone friendly and encouraging here..

**Comment by samkuhn** [comment]
> @samkuhn any chance you could delete your earlier message? It would be nice to keep the tone friendly and encouraging here..

Yes I did delete it? I've been through the wars with Expo and I mistakenly thought that this was a pull request for that repo. I apologise.

**Comment by ashishfeels** [comment]
@samkuhn it would be better if you read the repo name correctly next time. expo repos initials generally starts with the word "expo".

**Comment by Guichaguri** [comment]
@samkuhn Removing the Android service doesn't mean background mode won't work anymore, it will still play while the app is open and minimized, but it will stop as soon as the app is swiped from the task list (basically the same behavior as having the old `stopWithApp` option enabled)

**Comment by samkuhn** [comment]
Hi Guichaguri, Wouldn't the audio intermittently cut out while minimized though? That is what I found in my experience with no foreground service running to keep the audio alive (as per ExoPlayer team recommendations). 

I'd also like to apologise again for my tone this morning I totally thought this was a different repo and I've been a bit scarred with my android background audio experience there. But even so it was wrong to go in so hard and not my normal style. And definitely wasn't targeted at you @Guichaguri! Good luck with the implementation.

**Comment by Anitaislam** [comment]
open pulling

**Comment by kyleclegg** [comment]
How stable is this branch? Should we try shipping it to users from the commit and monitor?

**Comment by ashishfeels** [comment]
@kyleclegg  i am unfortunately not able to test this , but you can really test it by doing an A/B Test may be as the sample size will be quite bigger and if anything comes up up we can fix that before making the changes available to everyone. but its totally your choice. But this will helpful for devs & maintainers.

**Comment by Drazail** [comment]
@Guichaguri 

We used a rather similar approach to this at the start of our development cycle, however, Android used to be very aggressive with killing the app so we decided to go with your previous implementation. and so far ( after some minor tweaks) we haven't received any crash reports related to this library in months.

If you got any free time, please checkout my [fork](https://github.com/Drazail/react-native-track-player-1/tree/Drazail/android/src/main/java/com/guichaguri/trackplayer/service), it may provide some context to this comment. ( all of our media endpoints are mp3 files on s3, so this has not been tested for any other media types.)

**Comment by biomancer** [comment]
Hi @Guichaguri! For us these changes would mean that we would have to stick to some old version or fork forever, as it seems as there is no way to get tracks to reliably play in background if not using service approach. As you have pointed out, it is a big differential from other music modules and it was actually the main (or even the single) reason, why we started using react-native-track-player in the first place - the other solutions just did could not provide reliable background playback.

**Comment by bemnet4u** [comment]
Happy to test this. 

I already set stopWithApp=true since when the user kills the app, we need to kill audio as it seams the right thing to do...so not too worried about that.

**Comment by ashokkumar88** [comment]
I am getting the following error whey trying to play a track.

`com.facebook.react.bridge.ReadableNativeMap cannot be cast to com.facebook.react.bridge.JavaOnlyMap`

**Comment by abdelmagied94** [comment]
@Guichaguri Is the notification capabilities still working? As mentioned in the android [docs](https://developer.android.com/reference/androidx/media/session/MediaButtonReceiver), `MediaButtonReceiver` needs a service to receive `ACTION_MEDIA_BUTTON` intents.

**Comment by dcvz** [comment]
I will close this for now.. at the moment I don't believe the future of this library should be to disable the service.

Overall this is what allows us to build applications that can work in the background and not be killed by the system.. if there's such a need in the future, we'll re-evaluate.

**Pull request closed without merging**
