### PR TITLE
fix(ios): fix issues causing duplicate and/or inconsistent playback-track-changed events on iOS

### PR DESCRIPTION
**Pull request by jspizziri**
https://github.com/doublesymmetry/react-native-track-player/issues/1462, https://github.com/doublesymmetry/react-native-track-player/issues/1349

### CODE REVIEW

**Comment by jspizziri** [comment]
@dcvz 

This issue happens with `RepeatMode === Track`, and this seems to be the culprit. The reason being that `handleAudioPlayerQueueIndexChange` gets called once from the [queueIndex listener](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L30) and then again from [`handleAudioPlayerPlaybackEnded`](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L634) as a result of the [playbackEnded listener](https://github.com/doublesymmetry/react-native-track-player/blob/main/ios/RNTrackPlayer/RNTrackPlayer.swift#L26)

My guess is that there was a fix at some point in SwiftAudioEx fixed an issue where there was a missing `queueIndex` event in this scenario which caused an issue with a manual workaround that was put in place in this lib. Either way, in my testing this fix seems to work.

**Comment by jspizziri** [comment]
Alright, after looking into both this issue [and this one](https://github.com/doublesymmetry/react-native-track-player/issues/1349) its clear to me that there's a deeper problem here and that the two issues are interrelated.

I'm going to attempt to address both issues on this single PR and will be taking a more holistic look at both `playback-queue-ended` and `playback-track-changed` on both iOS & Android in _all_ repeat modes. Test cases to follow.

**Comment by jspizziri** [comment]
# Test Cases

----

## Single Track In Queue

###### 1. Repeat Mode Off

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | :white_check_mark: | ??? |
| `playback-track-changed` | :x: | ??? |

###### 2. Repeat Mode Track

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | :white_check_mark: | ??? |
| `playback-track-changed` | :white_check_mark: | ??? |

###### 3. Repeat Mode Queue

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | :white_check_mark: | ??? |
| `playback-track-changed` | :x: | ??? |

----

## Multiple Tracks In Queue

###### 1. Repeat Mode Off

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | ??? | ??? |
| `playback-track-changed` | ??? | ??? |

###### 2. Repeat Mode Track

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | ??? | ??? |
| `playback-track-changed` | ??? | ??? |


###### 3. Repeat Mode Queue

Result on last track end

| Event |  iOS  | Android |
|-------|-------|---------|
| `playback-queue-ended`   | :x: | ??? |
| `playback-track-changed` | :white_check_mark: | ??? |

**Comment by jspizziri** [comment]
Alright, I think I have this resolved, however there are two things I want to note:

1. [I created this bug based on the testing done here.](https://github.com/doublesymmetry/react-native-track-player/issues/1483) My guess is that it's a SwiftAudioEx issue. It's _possible_ that the fix for this will require an adjustment here.
2. It's strange to me that with a Multi-track queue in RepeatMode.Queue a `player.event.queueIndex` event index is called but that is **NOT** the case with a Single-track queue in RepeatMode.Queue. If this is found to be a bug in SwiftAudioEx then this PR will need to be adjusted accordingly.

CC @dcvz could use your insights on this.

**Comment by jspizziri** [comment]
## Notes (iOS)

1. In a multi-track queue with RepeatMode = Track. When a track plays to completion and repeats a `events.queueIndex` event is **NOT** fired.
1. In a multi-track queue with RepeatMode = Queue. When the _final_ track plays to completion and the player repeats a `events.queueIndex` event is **NOT** fired.
1. In a single-track queue with RepeatMode = Queue.  When the final track in the queue finishes playing it does **NOT** repeat.

**Comment by jspizziri** [comment]
rabbithole

My oh my, this rabbit hole ended up being far deeper than I'd imagined. There are a _lot_ of scenarios to cover that I hadn't anticipated. However, the most recent version of this PR seems to me to finally have parity with Android (or is hopefully close at the very least).

**Comment by dcvz** [comment]
Thanks a lot for the investigation @jspizziri!
I'm gonna start by setting up some tests to cover these cases in `SwiftAudioEx` -- we can then work towards resolving the likely failing tests.

**Comment by dcvz** [comment]
@jspizziri since we merged `kotlinaudio` we'll need to reopen this PR. Sorry!

**Comment by jspizziri** [comment]
Reopened https://github.com/doublesymmetry/react-native-track-player/pull/1501

**Pull request closed without merging**
