### PR TITLE
docs(config): Fix incorrect option description + link

### PR DESCRIPTION
**Pull request by mattleff**

### CODE REVIEW

**Comment by jspizziri** [comment]
@mattleff this LGTM, thanks! Could you please squash?

**Comment by mattleff** [comment]
@jspizziri Done.

**Comment by mattleff** [comment]
@jspizziri Sounds good! 👋🏻 from MT–I don't run into MT devs very often. 😀

**Review by dcvz — APPROVED** [review]

**Comment by jspizziri** [comment]
@mattleff we must band together 💪

**Comment by dcvz** [comment]
Thanks for the contribution @mattleff !

**Pull request merged**
