### PR TITLE
fix: added startForeground to onCreate

### LINKED ISSUE #620: [Android] Crash - android.app.RemoteServiceException
i am getting crash logs on playstore for some of the devices:
```
android.app.RemoteServiceException: 
  at android.app.ActivityThread$H.handleMessage (ActivityThread.java:1872)
  at android.os.Handler.dispatchMessage (Handler.java:106)
  at android.os.Looper.loop (Looper.java:214)
  at android.app.ActivityThread.main (ActivityThread.java:7045)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:493)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:965)
```
i tested on some of the devices it's working properly. i updated react native track player and target sdk version to 28. any idea why this crash happening ?

i am attaching Android versions and devices info on which crashes happens:

Screen Shot 2019-06-08 at 8 21 09 PM

### PR DESCRIPTION
**Pull request by Bang9**
resolve #620 #524 #473 #391

ANR graph changes since the fork was applied (released on 13 October 2020).
image

### CODE REVIEW

**Comment by Guichaguri** [comment]
We've made this changed in the past and it caused other crashes, I'd like to see more testing in different types of apps before merging this.

**Comment by dcvz** [comment]
@Bang9 how has this been working for you over this time?

**Comment by Bang9** [comment]
@dcvz I attached ANR graph
ANR seems to be spiking, but most recent occurrences are caused by other modules.

image
image

**Comment by dcvz** [comment]
We'll pull this in @Bang9 and we'll send it out with the next release v2.0.1 and we can see how the change performs in different apps.

**Pull request merged**
