### PR TITLE
Remove previous track on queue

### PR DESCRIPTION
**Pull request by ithustle**
Updating documentation related #1307

### CODE REVIEW

**Comment by jspizziri** [comment]
@ithustle Please keep everything related to that feature on the same PR. But issue the docs update as a separate commit. Thanks!

**Comment by ithustle** [comment]
@jspizziri its been while since I made that PR. I will close it and make a new one with changes on documentation. Sounds good?

**Comment by jspizziri** [comment]
@ithustle thats fine as long as we keep all changes pertaining to the same feature on the same PR (with separate commits)

**Comment by jspizziri** [comment]
@ithustle are you still working on this PR?

**Comment by jspizziri** [comment]
I'm closing due to inactivity.

**Pull request closed without merging**
