### PR TITLE
refactor(src): refactor the file structure for better organization

### PR DESCRIPTION
**Pull request by jspizziri**

### CODE REVIEW

**Comment by jspizziri** [comment]
@dcvz @mpivchev @puckey I'd appreciate all of your feedback on this one.

**Comment by puckey** [comment]
Yes, this looks good! I wonder however if replacing the default object export with individual exports is not a breaking change..

**Comment by jspizziri** [comment]
@puckey fair question. We are instructing people to import directly from the root, and not use deep imports from the `./trackPlayer` & `./interfaces` files. It would break things if people were doing deep exports like that for sure, however, everything is still exposed from the root in the exact same way it was before.

It also could just be something that lands in v4 too.

**Comment by jspizziri** [comment]
I've created a new PR based on @puckey 's work here https://github.com/puckey/react-native-track-player/pull/1

This one will likely get closed in favor of that one.

**Comment by jspizziri** [comment]
This ended up being done as part of https://github.com/doublesymmetry/react-native-track-player/pull/1713

**Pull request closed without merging**
