### PR TITLE
feat(android): move the jcenter dependency into the android library t…

### PR DESCRIPTION
**Pull request by jspizziri**
…o prevent installation issues

https://github.com/DoubleSymmetry/react-native-track-player/issues/1235#issuecomment-921266932

### CODE REVIEW

**Comment by jspizziri** [comment]
@mpivchev I think this MR should supersede this one: https://github.com/DoubleSymmetry/react-native-track-player/pull/1335

LMK what you think.

**Comment by dcvz** [comment]
@jspizziri does the `kotlinaudio` branch require `jcenter()`? I think this is only a problem for `main` currently since its based on an old release only available in `jcenter()`

**Comment by jspizziri** [comment]
@dcvz good question. I _thought_ I had run into this while using the `kotlinaudio` branch but let me check again and make sure. I'll let you know what I find.

**Comment by jspizziri** [comment]
@dcvz I just double checked and you're correct. I must've been switching between branches when I ran into this or something.

**Pull request closed without merging**
