### PR TITLE
[iOS] Pass minBuffer as the buffer size.

### PR DESCRIPTION
**Pull request by knyar**
This has been suggested in a few issues (#440, #970) but it seems that nobody has actually submitted a change.

### CODE REVIEW

**Comment by robinalexandre** [comment]
Did you try your changes ? 
Is it actually working if you set 15 sec on a long mp3 ?

Because for me, as I said in #970, it's not working.

**Comment by knyar** [comment]
I have confirmed that it gets set as the [preferredForwardBufferDuration](https://developer.apple.com/documentation/avfoundation/avplayeritem/1643630-preferredforwardbufferduration) property when a new [AVPlayerItem](https://developer.apple.com/documentation/avfoundation/avplayeritem) is created.

**Comment by robinalexandre** [comment]
I agree that it is set as the `preferredForwardBufferDuration` but the buffer which is then load does not correspond to the value. The question is: where does this problem come from ?

**Comment by knyar** [comment]
Just to confirm: I am seeing this change take effect and restrict the maximum size of the buffer for an `AVPlayerItem` that contains an HLS stream.

@robinalexandre, perhaps in your specific use case `preferredForwardBufferDuration` does not do what you expect it to do? I don't think this is something this library can really fix.

**Comment by robinalexandre** [comment]
I am using a default stream (mp3).
I expect the buffer to act the same for HSL or any over stream.

Could you please try with a mp3 and tell me your results to see if it comes from my side ?

**Comment by puckey** [comment]
Thanks for your PR!

According to the docs you referred to: "If set to `0`, the player will choose an appropriate level of buffering for most use cases."

In which case, would it not make more sense to default to `0` if no minBuffer is passed by the user?

**Comment by knyar** [comment]
`0` would be a reasonable default, however:
- at least for HLS streams `0` seem to mean that the player will keep buffering audio while it has available memory. This will be a big behaviour change compared to the previous buffer size (1 second).
- [Documentation.md](https://github.com/react-native-kit/react-native-track-player/blob/dev/docs/Documentation.md) describes the default to be 15 seconds. This is why I've decided to use this value.

I am happy to change the default to whatever value you think makes the most sense.

**Comment by ainformatico** [comment]
Hey guys! We actually forked and made the same change some time ago. Wanted to open a PR and saw this one :)
Any idea in which version we should expect this to be merged?

**Comment by Guichaguri** [comment]
> `0` would be a reasonable default, however:
> 
> * at least for HLS streams `0` seem to mean that the player will keep buffering audio while it has available memory. This will be a big behaviour change compared to the previous buffer size (1 second).
> * [Documentation.md](https://github.com/react-native-kit/react-native-track-player/blob/dev/docs/Documentation.md) describes the default to be 15 seconds. This is why I've decided to use this value.
> 
> I am happy to change the default to whatever value you think makes the most sense.

I think we should leave the default on iOS as `0`, just like 15 seconds is the default value on Android. These values also impact in memory usage, the default ones have been tested by the Android and iOS teams, which they know works well for their system.

**Comment by knyar** [comment]
I've changed the default to 0.

**Comment by lode** [comment]
I also would love to see this change in. Is there anything blocking releasing this I could help with?

**Comment by BjoernRave** [comment]
same here, would love to see this get merged :)

**Comment by dcvz** [comment]
thanks for this @knyar ! I have made these changes against the main branch (v2) #f16936a4be2c1acef2c930509138e3777544915a

**Pull request closed without merging**
