### PR TITLE
docs(guides): add some guides for common usecases of the app

### PR DESCRIPTION
**Pull request by jspizziri**

### CODE REVIEW

**Comment by dcvz** [comment]
@jspizziri looks like PR isn't done yet but seems we're adding docs for things only in 2.2.0 -- we'll have to wait until we've done the versioning split off I mentioned in #1479

**Comment by jspizziri** [comment]
For sure, I'm mostly just writing the guides right now. The necessary functionality hasn't even been merged haha. I just want a pr out there so I don't forget where I put it.

I was thinking that I can set up versioning as part of my progress event PR and then this could be rebased on that before merging.

**Comment by jspizziri** [comment]
Btw, it automatically requests a review from you when a pr is submitted, and you have to submit it before you can mark it as a draft, so that's why that happened that way.

**Comment by dcvz** [comment]
It didn't tag me. I just keep an eye on PR's now that there's not so many 😁

**Pull request closed without merging**
