### PR TITLE
fix(android): resolve asset

### PR DESCRIPTION
**Pull request by lovegaoshi**
since appcenter is being depreciated next year all the below context is no longer relevant
-----------
I have a problem where on android, after I deployed codepush, the custom icons in the notification area would fail to resolve and revert back to the default icons. While i'm not sure if this line fixes my codepush issue, I saw https://github.com/doublesymmetry/react-native-track-player/issues/2101 and https://github.com/doublesymmetry/react-native-track-player/issues/2188 which might be a related asset resolving problem, and from a glance the example app's pure(demo) works again.
@puckey i have no idea how resolveAssetSource works

might fix https://github.com/doublesymmetry/react-native-track-player/issues/2101
might fix https://github.com/doublesymmetry/react-native-track-player/issues/2188 

----
after some stupidity I realized I thought my line works but its bc my metro is somehow caching build results - no wonder why i built in 3 seconds. After some frustrations I found out the return type of locally imported assets must be {uri: string} to work in android (still unsure what caused my particular codepush issue, or if custom icon is failing as a result), but not in `<Image>`.

I think Track.artwork needs to be string | assetResource (?) for ts type annotation, but its a TODO now

### CODE REVIEW

**Comment by lovegaoshi** [comment]
just did a release build on my app with this fix, notif area custom icon doesnt break; probably trying out codepush later

**Comment by lovegaoshi** [comment]
seems to also fix https://github.com/doublesymmetry/react-native-track-player/issues/2103 because updateMetadataForTrack, updateNowPlayingMetadata both uses resolveImportedAssetOrPath

**Comment by lovegaoshi** [comment]
unfortunately no it doesnt fix the codepushed asset resolve:(

**Comment by andordavoti** [comment]
This fixed my issue where Android prod didn't play audio. Thanks a lot for the help:)

**Comment by itsramiel** [comment]
@lovegaoshi Do you have any insights as to why it before your change it was working on debug but not release? The change fixes it for me but I am curious why?

**Comment by itsramiel** [comment]
@dcvz could you please take a look? Not loading a local file in release is definitely a bug

**Comment by lovegaoshi** [comment]
in dev imported sources is bundled a 8081 "weblink“ so this string is
queried as an web address without a problem; in release this is a number
representing the bundled resources and exoplayer needs the uri identifier
to specify it
thats my guess. my other problem is what happens when codepush comes into
play - it seems to work for some bundled resources but not others
(specifically notification manager icons)

**Comment by jaegwans** [comment]
> 이로 인해 Android 제품이 오디오를 재생하지 못하는 문제가 해결되었습니다. 도움을 주셔서 감사합니다 :)

me too

**Comment by jmarsh24** [comment]
I just ran into this issue on android after the android simulator worked and iOS fully works. sourcing my react native track player package from this repo fixed the issue. This PR seems to be working but has not been merged to master. I'm commenting to acknowledge that this has been tested and is working in production. 

Please merge for others.

**Review by dcvz — APPROVED** [review]
LGTM 👍

**Pull request merged**
