### PR TITLE
Add support for web

### PR DESCRIPTION
**Pull request by kvnp**
This PR is a highly experimental implementation of react-native-track-player for web. I think having support for web would be a great addition. What are your thoughts?

### CODE REVIEW

**Comment by bradleyflood** [comment]
My thoughts... given development capacity is already limited for RNTP, adding another supported platform (web) adds more complexity, more surface area for bugs, more documentation, and  maintainer time required. 

I assume the majority of use cases are going to be iOS and Android. Web usage of RN is very small.

**Comment by jspizziri** [comment]
@kvnp thanks for this PR!

I've actually been working on a web implementation myself. I wonder if you'd be interested in combining efforts.

There are a few differences I have under the hood, the main one being that my web player so far is built around shaka-player so that things like DRM can be supported.

I'm working on publishing a branch on our fork in the next few days. I'm wondering if once I do if we could take a look to see how we can merge the two approaches.

**Comment by jspizziri** [comment]
@kvnp you can see my work thus far here: https://github.com/5-stones/react-native-track-player/pull/5

**Comment by jspizziri** [comment]
@kvnp 

> This looks really promising! As far as I can tell this is a full implementation, right? Are there any bugs or limitations that might need some looking into? I will definitely try this out in the following days.

There are certainly bugs 😜 , although I don't know of any at the moment. I think it's relatively complete at this point, at least it is for how I use RNTP. I'd recommend you check it out and let me know what you find. We're currently [publishing it to npm here](https://www.npmjs.com/package/@5stones/react-native-track-player/v/4.0.0-web.6). Check out the `4.0.0-web.6` version (they're all being published under `4.0.0-web.x` tags.

**Comment by kvnp** [comment]
> There are certainly bugs 😜 , although I don't know of any at the moment. I think it's relatively complete at this point, at least it is for how I use RNTP. I'd recommend you check it out and let me know what you find. We're currently [publishing it to npm here](https://www.npmjs.com/package/@5stones/react-native-track-player/v/4.0.0-web.6). Check out the `4.0.0-web.6` version (they're all being published under `4.0.0-web.x` tags.
Thanks! I tested it immediately after seeing your npm link!

Using your implementation I had trouble getting my music to playback at first. I'm mostly using audio/mp4 streams via googlevideo or as blobs. I fixed it by making sure the property contentType is set for all my Track objects and adding it to shaka.Player.load().

Skipping is broken for me as well. The events seem to have changed a bit since my PlaybackService relies on them to update URLs dynamically. Is the documentation going to be updated soon so I can adapt my app to those changes?

**Comment by jspizziri** [comment]
@kvnp ahh yes. That branch is built on top the work that's been done for 4.0.0, so it has breaking changes. There's no formal documentation right now, but you can look at the comments on this PR https://github.com/doublesymmetry/react-native-track-player/pull/1713

You can also look at the example app on my branch, which has been updated to use the new API.

I would encourage moving the discussion over there!

**Comment by jspizziri** [comment]
@kvnp I'm closing this PR in favor of one based the implementation I've been working on.

https://github.com/doublesymmetry/react-native-track-player/pull/1886

**Pull request closed without merging**
