### PR TITLE
Add missing promise resolve in iOS destroy method

### PR DESCRIPTION
**Pull request by mmmoussa**
Fixes https://github.com/DoubleSymmetry/react-native-track-player/discussions/1264#discussioncomment-2407544 on iOS.

Before the change:
`await TrackPlayer.destroy()` never resolves

After the change:
`await TrackPlayer.destroy()` resolves and following code continues execution

### CODE REVIEW

**Comment by mpivchev** [comment]
@dcvz On Android we are also not resolving the callback:

```kotlin
    @ReactMethod
    fun destroy(callback: Promise) {
        if (verifyServiceBoundOrReject(callback)) return

        unbindService()
        musicService.destroyIfAllowed(true)
    }
```

Is this something we missed?

**Comment by dcvz** [comment]
@mpivchev it does seem like something we missed. Looks like we only added a rejection but not completion.

**Comment by dcvz** [comment]
@mmmoussa this is against the wrong branch -- you want to target the `kotlinaudio` branch

**Comment by jspizziri** [comment]
I created an PR that adds the outstanding android fix and is based off of kotlinaudio https://github.com/doublesymmetry/react-native-track-player/pull/1472.

**Pull request closed without merging**
