### PR TITLE
fix(android): move the kotlin-gradle-plugin dependency into the libra…

### PR DESCRIPTION
**Pull request by jspizziri**
…ry dependencies

The kotlin-gradle-plugin dependency needs to be specified by the library so that it's not required to add it as a dependency of users projects.

### CODE REVIEW

**Comment by jspizziri** [comment]
@dcvz @mpivchev,

Just a heads up you on this. It would be great to get this into an `rc` release. Without this change, each user of the lib would need to modify their project `build.gradle` to specify the dependency at a global level.

**Comment by jspizziri** [comment]
cc @bradleyflood  https://github.com/DoubleSymmetry/react-native-track-player/issues/1371

**Review by mpivchev — APPROVED** [review]
LGTM! Thanks for this :)

**Comment by jspizziri** [comment]
@mpivchev thanks! Could we get a new RC released?

**Comment by jspizziri** [comment]
Also @dcvz @mpivchev ,

We use this project pretty heavily right now. I know everyone is busy and so I'd like to formally offer my help in maintaining the project if you'd like it. But I can certainly cut a new release myself if I had write access to the repository and npm package. If not, no big deal, just wanted to offer.

**Comment by mpivchev** [comment]
> @mpivchev thanks! Could we get a new RC released?

Will do this today :)

**Comment by mpivchev** [comment]
> Also @dcvz @mpivchev ,
> 
> We use this project pretty heavily right now. I know everyone is busy and so I'd like to formally offer my help in maintaining the project if you'd like it. But I can certainly cut a new release myself if I had write access to the repository and npm package. If not, no big deal, just wanted to offer.

We will update you on that.

**Comment by dcvz** [comment]
`rc-3` is out now incorporating this change, full change log tomorrow

**Pull request merged**
