### PR TITLE
fix(ios, events): fix an issue with PlaybackQueueEnded resulting from…

### PR DESCRIPTION
**Pull request by jspizziri**
… a race condition

https://github.com/doublesymmetry/react-native-track-player/issues/1598

### CODE REVIEW

**Comment by jspizziri** [comment]
This fixes a race condition affecting the `PlaybackQueueEnded` event on iOS. Previously we were firing this event based off of the `playbackEnd` event. When that event was fired we were checking to see if the queue had more items left to play by evaluating `player.nextItems.count`. However, this property was evaluating incorrectly due to a race condition. By the time the handler gets called, the `nextItem.count` has already been updated by the `player` so it can be off by a value of `1`.

This was causing the `PlaybackQueueEnded` event to be fired on both the `n` **AND** the `n - 1` track transitions.

I fixed it by moving the event firing to the `PlaybackTrackChanged` handler, which is more consistent.

**Comment by jspizziri** [comment]
@dcvz running one more test on this.

**Comment by jspizziri** [comment]
@dcvz so everything was working fine, but I decided to change `player.currentIndex` to `index` when firing the event. I wasn't seeing it but I realized this could be a race condition as well. It's safer to do it this way as that's the value we're using in the `track-changed` event too.

Sorry for triggering another 20min iOS build :/. Should've thought of that on initial implementation.

**Comment by jspizziri** [comment]
@dcvz ready for another approval

**Comment by trm217** [comment]
@dcvz Could you please consider releasing patch versions when ever such rather substancial bugs are fixed?

**Pull request merged**
